# This file specifies your Python application's runtime configuration
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details.

# TODO: Enter your application id below. If you have signed up
# using cloud.google.com/console use the "project id" for your application
# id.
application: tvmayirp-byte2
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /js
  static_dir: js
  application_readable: true
- url: /fonts
  static_dir: fonts
  application_readable: true
- url: /css
  static_dir: css
  application_readable: true
- url: /templates
  static_dir: templates
  application_readable: true
- url: /images
  static_dir: images
  application_readable: true

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest
- name: ssl
  version: latest
